### ISSUE TITLE
[Crash]: Crash on Server Start (Fabric

### ISSUE THREAD

**Issue by suerion** [Fuzss/enderzoology#27]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

v21.1.0

### Minimal Setup

No

### Notes (Required)

On start from my Server, it does Crash with this error:
```
[20:04:29] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'enderzoology' at 'fuzs.enderzoology.fabric.EnderZoologyFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.5.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.5-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.IllegalStateException: Duplicate DefaultAttributes entry: entity.enderzoology.concussion_creeper
        at fuzs.puzzleslib.fabric.impl.core.context.EntityAttributesCreateContextFabricImpl.registerEntityAttributes(EntityAttributesCreateContextFabricImpl.java:16) ~[PuzzlesLib-v21.1.9-1.21.1-Fabric.jar:?]
        at fuzs.enderzoology.EnderZoology.onEntityAttributeCreation(EnderZoology.java:133) ~[EnderZoology-v21.1.0-1.21.1-Fabric.jar:?]
        at fuzs.puzzleslib.fabric.impl.core.FabricModConstructor.registerLoadingHandlers(FabricModConstructor.java:39) ~[PuzzlesLib-v21.1.9-1.21.1-Fabric.jar:?]
        at fuzs.puzzleslib.fabric.impl.core.FabricModConstructor.construct(FabricModConstructor.java:23) ~[PuzzlesLib-v21.1.9-1.21.1-Fabric.jar:?]
        at fuzs.puzzleslib.fabric.impl.core.FabricFactories.constructMod(FabricFactories.java:32) ~[PuzzlesLib-v21.1.9-1.21.1-Fabric.jar:?]
        at fuzs.puzzleslib.api.core.v1.ModConstructor.construct(ModConstructor.java:36) ~[PuzzlesLib-v21.1.9-1.21.1-Fabric.jar:?]
        at fuzs.enderzoology.fabric.EnderZoologyFabric.onInitialize(EnderZoologyFabric.java:11) ~[EnderZoology-v21.1.0-1.21.1-Fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
        ... 7 more
```

### Crash Report (Required)

no crash report, only crash on startup

### latest.log (Optional)

https://mclo.gs/6kXfzTJ

**Comment by Fuzss** [comment]
Does it happen every time or randomly?

**Comment by suerion** [comment]
Hey, i had tried to start 10 times, it is always there

**Comment by Fuzss** [comment]
Please try this version and send the `latest.log` from that.

https://mega.nz/file/ncVkkZLb#mVNl0HAOfcxdzfuYg3eblvZKRVWmFQOeSGe2YOomLZY

**Comment by suerion** [comment]
Hey, here is the latest 

https://mclo.gs/4TXL6Le

**Comment by suerion** [comment]
> How about this Puzzles Lib? Shouldn't matter which Ender Zoology you have. https://mega.nz/file/XddCCTjT#oit5o2DbxblVMWwrH5L-uII4Y8ZZJQTTFLS9M4AXCRE

With this Puzzle Lib the server starts correctly

**Comment by Fuzss** [comment]
Will release that publicly soon then.

**Comment by suerion** [comment]
Thanks for help :)
