### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by mervy-n** [Fuzss/enderzoology#7]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

5.0.0

### Exploding the custom TNT causes a server crash

```
29.06 19:33:06 [Server] Server thread/[ERROR] Encountered an unexpected exception
29.06 19:33:06 [Server] [INFO] net.minecraft.class_148: Ticking entity
29.06 19:33:06 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]
29.06 19:33:06 [Server] [INFO] Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
29.06 19:33:06 [Server] [INFO] at fuzs.enderzoology.world.level.EnderExplosion$EntityInteraction.createEffects(EnderExplosion.java:192) ~[EnderZoology-v5.0.0-1.19.3-Fabric.jar:?]
29.06 19:33:06 [Server] [INFO] at fuzs.enderzoology.world.level.EnderExplosion.method_8350(EnderExplosion.java:165) ~[EnderZoology-v5.0.0-1.19.3-Fabric.jar:?]
29.06 19:33:06 [Server] [INFO] at fuzs.enderzoology.world.level.EnderExplosion.explode(EnderExplosion.java:63) ~[EnderZoology-v5.0.0-1.19.3-Fabric.jar:?]
29.06 19:33:06 [Server] [INFO] at fuzs.enderzoology.world.level.EnderExplosion.explode(EnderExplosion.java:54) ~[EnderZoology-v5.0.0-1.19.3-Fabric.jar:?]
29.06 19:33:06 [Server] [INFO] at fuzs.enderzoology.world.entity.item.PrimedCharge.method_5773(PrimedCharge.java:45) ~[EnderZoology-v5.0.0-1.19.3-Fabric.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_3218.method_18762(class_3218.java:728) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_1937.method_18472(class_1937.java:482) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_3218.method_31420(class_3218.java:374) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_3218.method_18765(class_3218.java:342) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] ... 5 more
29.06 19:33:06 [Server] [INFO] Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
29.06 19:33:06 [Server] [INFO] at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
29.06 19:33:06 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
29.06 19:33:06 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
29.06 19:33:06 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
29.06 19:33:06 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
29.06 19:33:06 [Server] [INFO] at fuzs.enderzoology.world.level.EnderExplosion$EntityInteraction.createEffects(EnderExplosion.java:192) ~[EnderZoology-v5.0.0-1.19.3-Fabric.jar:?]
29.06 19:33:06 [Server] [INFO] at fuzs.enderzoology.world.level.EnderExplosion.method_8350(EnderExplosion.java:165) ~[EnderZoology-v5.0.0-1.19.3-Fabric.jar:?]
29.06 19:33:06 [Server] [INFO] at fuzs.enderzoology.world.level.EnderExplosion.explode(EnderExplosion.java:63) ~[EnderZoology-v5.0.0-1.19.3-Fabric.jar:?]
29.06 19:33:06 [Server] [INFO] at fuzs.enderzoology.world.level.EnderExplosion.explode(EnderExplosion.java:54) ~[EnderZoology-v5.0.0-1.19.3-Fabric.jar:?]
29.06 19:33:06 [Server] [INFO] at fuzs.enderzoology.world.entity.item.PrimedCharge.method_5773(PrimedCharge.java:45) ~[EnderZoology-v5.0.0-1.19.3-Fabric.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_3218.method_18762(class_3218.java:728) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_1937.method_18472(class_1937.java:482) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_3218.method_31420(class_3218.java:374) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.class_3218.method_18765(class_3218.java:342) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
29.06 19:33:06 [Server] [INFO] ... 5 more
29.06 19:33:06 [Server] Server thread/[ERROR] This crash report has been saved to: /./crash-reports/crash-2023-06-29_19.33.06-server.txt
29.06 19:33:06 [Server] Server thread/[INFO] Votifier stopped.
29.06 19:33:06 [Server] Thread-57/[ERROR] Protocol error. Ignoring packet - Socket closed
29.06 19:33:06 [Server] Server thread/[INFO] Starting shutdown process...
29.06 19:33:06 [Server] Server thread/[INFO] Closing storage...
29.06 19:33:06 [Server] Server thread/[INFO] Goodbye!
29.06 19:33:06 [Server] Server thread/[INFO] Stopping server
29.06 19:33:06 [Server] Server thread/[INFO] Saving players
29.06 19:33:06 [Disconnect] User hellbegins has disconnected, reason: Server closed
29.06 19:33:06 [Server] Server thread/[INFO] [ADMIN] hellbegins left the game
29.06 19:33:06 [Server] Server thread/[INFO] Saving worlds
29.06 19:33:08 [Server] Server thread/[INFO] Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
29.06 19:33:08 [Server] Server thread/[INFO] Saving chunks for level 'ServerLevel[world]'/sculk_depths:sculk_depthsdim
29.06 19:33:08 [Server] Server thread/[INFO] Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
29.06 19:33:08 [Server] Server thread/[INFO] Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
29.06 19:33:08 [Server] Server thread/[INFO] ThreadedAnvilChunkStorage (world): All chunks are saved
29.06 19:33:08 [Server] Server thread/[INFO] ThreadedAnvilChunkStorage (sculk_depthsdim): All chunks are saved
29.06 19:33:08 [Server] Server thread/[INFO] ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
29.06 19:33:08 [Server] Server thread/[INFO] ThreadedAnvilChunkStorage (DIM1): All chunks are saved
29.06 19:33:08 [Server] Server thread/[INFO] ThreadedAnvilChunkStorage: All dimensions are saved
29.06 19:33:08 [Server] C2ME Storage #3/[INFO] Storage thread Thread[C2ME Storage #3,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #2/[INFO] Storage thread Thread[C2ME Storage #2,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #1/[INFO] Storage thread Thread[C2ME Storage #1,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #5/[INFO] Storage thread Thread[C2ME Storage #5,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #6/[INFO] Storage thread Thread[C2ME Storage #6,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #4/[INFO] Storage thread Thread[C2ME Storage #4,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #9/[INFO] Storage thread Thread[C2ME Storage #9,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #8/[INFO] Storage thread Thread[C2ME Storage #8,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #7/[INFO] Storage thread Thread[C2ME Storage #7,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #12/[INFO] Storage thread Thread[C2ME Storage #12,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #11/[INFO] Storage thread Thread[C2ME Storage #11,8,main] stopped
29.06 19:33:08 [Server] C2ME Storage #10/[INFO] Storage thread Thread[C2ME Storage #10,8,main] stopped
```

### Crash Report (Required)

https://gist.github.com/mervy-n/c777e40708b00567aa76ce49aa13f416

**Comment by Fuzss** [comment]
This is fixed for 1.20.1, still need to backport to 1.19.2. 1.19.3 is not supported anymore.
